name: Custom Tasks

on:
  workflow_dispatch:

permissions: write-all

jobs:
  testjobA:
    runs-on: windows-latest
    steps:
      - name: Should succeed
        run: echo "This is attempt; ${{ github.run_attempt }}"
        shell: pwsh

  testjobB:
    needs: testjobA
    runs-on: windows-latest
    steps:
      - name: Should Fail
        run: exit 1
        shell: pwsh

  aftermath:
    needs: testjobB
    runs-on: windows-latest
    if: failure()
    steps:
      - name: Should run after testjobB
        run: echo "This is the aftermath"
        shell: pwsh
