name: Custom Tasks

on:
  workflow_dispatch:

permissions: write-all

jobs:
  testjobA:
    runs-on: windows-latest
    if: always()
    steps:
      - name: Should succeed
        run: echo "This is attempt; ${{ github.run_attempt }}"
        shell: pwsh

  testjobB:
    needs: [testjobA]
    runs-on: windows-latest
    if: always()
    steps:
      - name: Should Fail
        run: exit 1
        shell: pwsh
