name: Custom Tasks

on:
  workflow_dispatch:

permissions: write-all

jobs:
  testjobA:
    runs-on: windows-latest
    steps:
      - name: Should succeed
        run: echo "Hello, world!"
        shell: pwsh

  testjobB:
    needs: [testjobA]
    runs-on: windows-latest
    steps:
      - name: Should Fail
        run: exit 1
        shell: pwsh
