name: Observe Lab

on:
  workflow_call:
    inputs:
      lab-matrix:
        description: "Lab jobs to observe"
        required: true
        type: string
jobs:
  wait-for-lab-operator:
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(inputs.lab-matrix) }}
    name: Waiting for the checkpoint reset
    runs-on: windows-latest
    steps:
    - name: Did every entry in lab-matrix get an assigned master?
      run: |
        $headers = @{
          "secret" = ${{ secrets.NETPERF_SYNCER_SECRET }}
        }
        $clientApi = "https://netperfapi.azurewebsites.net/getkeyvalue?key=${{ github.run_id }}_${{ matrix.env_str }}_labclient_reset"
        $serverApi = "https://netperfapi.azurewebsites.net/getkeyvalue?key=${{ github.run_id }}_${{ matrix.env_str }}_labserver_reset"
        while ($true) {
          try {
            $clientResponse = Invoke-RestMethod -Uri $clientApi -Headers $headers
            $serverResponse = Invoke-RestMethod -Uri $serverApi -Headers $headers
            if ($clientResponse.StatusCode -neq 200 -or $serverResponse.StatusCode -neq 200) {
              throw "Not ready"
            }
            break
          } catch {
            Write-Host "Waiting for the checkpoint reset..."
            Start-Sleep -Seconds 30
          }
        }
      shell: pwsh
