name: Observe Lab

on:
  workflow_call:
    inputs:
      lab-matrix:
        description: "Lab jobs to observe"
        required: true
        type: string
      project:
        description: "The project dispatch workflows to"
        required: true
        type: string
jobs:
  lab-observer:
    name: Current Lab State
    runs-on: windows-latest
    steps:
    - name: Observe Job Status
      run: |
        $lab_matrix = ConvertFrom-Json ${{ inputs.lab-matrix }}
        # Dispatch Test Job Workflow


      shell: pwsh
