name: Operate Lab

on:
  workflow_call:
    inputs:
      lab-matrix-filename:
        description: "Matrix of jobs and their respective environments"
        required: false
        default: "lab-matrix.json"
        type: string
    outputs:
      lab-matrix:
        description: "The full list of jobs to be run in secnetperf"
        value: ${{ jobs.prepare-matrix.outputs.lab-matrix }}
      azure-matrix:
        description: "The list of jobs to be run on Azure VMs"
        value: ${{ jobs.prepare-matrix.outputs.azure-matrix }}
      full-matrix:
        description: "The full list of jobs to be run in secnetperf"
        value: ${{ jobs.prepare-matrix.outputs.full-matrix }}

permissions: write-all

jobs:
  prepare-lab-server:
    name: Prepping the server machine
    outputs:
      lab-matrix: ${{ steps.generate-lab-matrix.outputs.matrix }}
      azure-matrix: ${{ steps.generate-azure-matrix.outputs.matrix }}
      full-matrix: ${{ steps.generate-full-matrix.outputs.matrix }}
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Prepare Matrix
      run: ./.github/workflows/prepare-matrix.ps1
    - id: generate-lab-matrix
      run: echo "matrix=$(jq -c '.' ./.github/workflows/lab-matrix.json)" >> $GITHUB_OUTPUT
      shell: bash
    - id: generate-azure-matrix
      run: echo "matrix=$(jq -c '.' ./.github/workflows/azure-matrix.json)" >> $GITHUB_OUTPUT
      shell: bash
    - id: generate-full-matrix
      run: echo "matrix=$(jq -c '.' ./.github/workflows/full-matrix.json)" >> $GITHUB_OUTPUT
      shell: bash

 prepare-lab-client:

 observer:

