name: Operate Lab

on:
  workflow_call:
    inputs:
      lab-matrix:
        description: 'The serialized matrix of values to use for the composite action.'
        required: true
        type: string

permissions: write-all

jobs:
  operate-lab-server:
    name: Reverting Server Machine
    runs-on:
      - self-hosted
      - Windows
      - x64
    steps:
      - name: Hello
        run: echo "Hello, world!"

  observer:
    name: Observer
    runs-on: windows-latest
    steps:
      - name: Hello
        run: echo "Hello, world!"

  operate-lab-client:
    needs: [observer]
    name: Reverting Client Machine
    runs-on:
      - self-hosted
      - parent=${{ env.PARENT_LABEL }}
    steps:
      - name: Hello
        run: echo "Hello, world!"

