# TODO: Always, as a final step before shutting down, run a step that prints out the workflow URL of the child VM perf test workflow for later consumption.


name: Operate Lab

on:
  workflow_call:
    inputs:
      lab-matrix:
        description: 'The serialized matrix of values to use for the composite action.'
        required: true
        type: string

permissions: write-all

jobs:
  operate-lab-master: # Consume lab matrix, advertise to the compatible masters, run master jobs.
    name: Finding a Master
    strategy:
      matrix: ${{fromJson(inputs.lab-matrix)}}
    runs-on:
      - self-hosted
      - Windows
      - x64
      - lab-stateless
      - os-${{ matrix.os }}
    steps:
      - name: Dispatch the slave workflow
        run: |
          # Use the Github API to trigger slave workflow
          $headers = @{
            "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
            "Accept" = "application/vnd.github.v3+json"
          }
          $body
      - name: Revert Checkpoint
        run: |
          $vmName = "netperf-${{ matrix.os }}-server"
          $checkPointName = "LATEST"
          Restore-VMSnapshot -VMName $vmName -Name $checkPointName -Confirm:$false
      - name: Start VM and wait for online status
        run: |
          $vmName = "netperf-${{ matrix.os }}-server"
          Start-VM -Name $vmName
          Wait-VMOnline -VMName $vmName
          $headers = @{
            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
          }
      - name: Wait for a status update from the test jobf
        run: |
          $headers = @{
            "secret" = "${{ secrets.NETPERF_SYNCER_SECRET }}"
          }

