name: Operate Lab

on:
  workflow_call:
    inputs:
      lab-matrix:
        description: 'The serialized matrix of values to use for the composite action.'
        required: true
        type: string

permissions: write-all

jobs:
  operate-lab-server:
    name: Reverting Server Machine
    strategy:
      matrix:
        include:
    runs-on:
      - self-hosted
      - windows
      - x64
      - {{}}

  observer:
    name: Observer
    runs-on: windows-latest
    steps:

  operate-lab-client:
    needs: [observer]
    name: Reverting Client Machine
    runs-on:
      - self-hosted
      - parent=${{ env.PARENT_LABEL }}
    steps:

