name: UpdateReact

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: [ "dashboard/**", ".github/workflows/update-react.yml" ]
  pull_request:
    branches:
      - main
    paths: [ "dashboard/**", ".github/workflows/update-react.yml" ]

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: update-react-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
  
jobs:
  npm-build:
    name: Npm build
    needs: []
    strategy: 
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      with:
        repository: microsoft/netperf
        ref: main
    - run: cd dashboard
    - run: npm install
    - run: npm run build
    - name: Upload Dist
      if: ${{ always() }}
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: dist
        path: dist

  update-react:
    permissions: write-all
    name: Update React
    needs: [npm-build]
    strategy: 
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      with:
        repository: microsoft/netperf
        ref: deploy
    - run: rm -rf dist
    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: dist
        path: dist

    - name: Commit changes
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch')
      run: |
        git config user.name 'QUIC Dev[bot]'
        git config user.email 'quicdev@microsoft.com'
        git add dist 
        git status
        git commit -m "Update React"
        git push
